language: ruby
rvm:
- 2.1.5
notifications:
  slack:
    secure: yQ07GymZCoK5B+YTcDZBuEoOsRujCMqOxhAVFTz96FNzn2afuhWlXhvL1io7jWjCjbJ7KbKgwsDOXI2iC5WPXI4aK5r9AgaEz1KKngsYHx6ZCeVCzbGoKoKot6/QLhuIMfAwxfCRwp412uF22Toj4Jf7gYZ9hvmeCaJrd8OwN5P4HU1XchxFnW2x9KQAbrSwzShFTyQ+FNYPPVA/JGraG2lgiP1d4oIXGtmoD00KFOkSqHsgOfiVFivCnqWC+1cLvwPmcFmUGNr9JbKbFhWGVCBuifNeXNG9xHtmy2MNBA79tejIx+mdOsZaDgg9ArL76jipElKy168qS414pLxvmyh38/yfq3Bu6OMzdDDQy/hsXfsFZtS223vRVD0Mi37IFCRue1CDknBvzNlYu52qhxzxG++zthIe+5oY7h7FpbIwntngm+uX6kYpMlJXMWD9oh4KSpX0OqidkQ3eU6k2eiaD8d1r04XPo2Zy7zFURnifPEQGJtZe2QYqf7jWY3SvkSgWgTEASjSfYYe831kTvc7a16EaPYI2s40kLg+bLeMUC5Jqeh94m7TYBANYM464dd4LBaB4e2e4CT7Y3BdkL3JBnuTBslzbMhQ6bOtx77MDOa+nXTXcpCgV+CvFgqTo++zkx3yqNtP8sWDrx8g9+cPlmCXEkTRjTP93JbF7IJo=
